services:
  pwn-06:
    build: .
    ports:
      - "10102:5000"
    restart: always
    privileged: true
    environment:
      JAIL_TIME: "30"
      JAIL_MEM: "64M"
      JAIL_PIDS: "5"
      JAIL_CPU: "100"
      JAIL_PORT: "5000"
      JAIL_FLAG: "FLAG{sh3llc0d3r_go_brrrr}"
      JAIL_FLAG_PATH: "/app/flag.txt"
      JAIL_CGROUP_MEM_MAX: "67108864"
